services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: