import type { Metadata } from 'next';
import './globals.css';
import { CustomSessionProvider } from '@/components/CustomSessionProvider';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <CustomSessionProvider>{children}</CustomSessionProvider>
      </body>
    </html>
  );
}
