import type { Metadata } from "next";
import "./globals.css";
import { CustomSessionProvider } from "@/components/CustomSessionProvider";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Navbar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
      >
        <Navbar />
        <CustomSessionProvider>{children}</CustomSessionProvider>
      </body>
    </html>
  );
}
